Update tabs and create tabs tasks
NikitaBondarevv/todo pull request #3
Opened 2022-12-06 17:58 UTC by NikitaBondarevv

2022-12-09 09:06 UTC, iliatsymbal requested changes

2022-12-09 09:06 UTC, iliatsymbal commented on src/taskList/index.js
> +      <div className={styles.content}>
where is `.content` class in styles?

2022-12-09 10:14 UTC, NikitaBondarevv commented on src/editableText/index.js
> +      <div>
Not needed, empty tags can be used

2022-12-09 11:03 UTC, iliatsymbal commented on src/editableText/index.js
> +      <div>
and why do you need an empty tag?

2022-12-10 17:23 UTC, iliatsymbal commented on src/editableText/index.js
> +      <>
why do you need react fragment here?

2022-12-11 17:52 UTC, iliatsymbal commented on src/editableText/index.js
> +      hidden ? <span onClick={this.showInput}>{value ? value : this.props.text}</span> :
`value ? value : this.props.text` use more appropriate logical operator

2022-12-11 19:10 UTC, merged